services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: ${NGINX_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${NGINX_PORT_OUT}:${NGINX_PORT}
      - ${NGINX_SSL_OUT}:${NGINX_SSL}
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
      # Default directory.
      #- :/usr/share/nginx/html
    #env_file:
    #  - ./.env

  fastapi-app:
    image: ${FASTAPI_IMAGE_NAME}:${PROJECT_VERSION}
    container_name: ${FASTAPI_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile.dev
      args:
        FASTAPI_APP_NAME: ${PROJECT_NAME}
        FASTAPI_PORT: ${FASTAPI_PORT}
        FASTAPI_SRC_DIR: ${FASTAPI_SRC_DIR}
      #command: sh -c ""
    restart: unless-stopped
    ports:
      - ${FASTAPI_PORT_OUT}:${FASTAPI_PORT}
    volumes:
      - ./src${FASTAPI_SRC_DIR}:/app
    environment:
      - FASTAPI_ENV=development
    #env_file:
    #  - ./.env
    depends_on:
      - nginx