# Base image.
FROM python:3.12.5-alpine

# Set evironment variables.
ENV LANG=C.UTF-8

# Import Arguments
ARG PYTHON_PORT

# Set up working directory.
WORKDIR /app

# Copy
COPY ./src .

# Install packages.
RUN 

# Copy source.
COPY ./src .

# Document exposed port.
EXPOSE ${PYTHON_PORT}

# Start app.